return {
  require 'oldvim.plugins.common',
  require 'oldvim.plugins.noice',
  require 'oldvim.plugins.whichkey',
  require 'oldvim.plugins.mini',
  require 'oldvim.plugins.miniline',
  require 'oldvim.plugins.lualine',
  require 'oldvim.plugins.completion',
  require 'oldvim.plugins.lsp',
  require 'oldvim.plugins.format',
  require 'oldvim.plugins.telescope',
  require 'oldvim.plugins.treesitter',
  require 'oldvim.plugins.oil',
  require 'oldvim.plugins.dashboard',
  require 'oldvim.plugins.bufferline',
  require 'oldvim.plugins.neo-tree',
  require 'oldvim.plugins.persistant',
}
